### ISSUE TITLE
Hashtags working on matrix anwsers

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-indices#48]
El módulo SAT hackea las encuestas. 
Este hackeo, tiene en cuenta los hashtags de las respuestas en las preguntas. 
Debería poder funcionar también en el tipo de respuestas:
Matriz - Opción simple
Matriz - Opción múltiple

https://participate.indices-culture.eu/admin/participatory_processes/selfassessmenttool/components/94/manage/

**Comment by agustibr** [comment]
This feature was merged and deployed with #51
