### ISSUE TITLE
Mejorar la página de feedback text

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-indices#49]
Actualmente la página de feedback text es esta:
![imatge](https://user-images.githubusercontent.com/40388743/158414500-db351ab8-f2f0-4294-b8a2-7f8bafa762f7.png)

@nadning he preparado con mucho amor el siguiente mockup:
![mockup_feedback_text_sat](https://user-images.githubusercontent.com/40388743/158414830-1b4f6878-4c7a-4655-93c9-d704159e319d.png)

**Comment by microstudi** [comment]
@paarals A mira, voy tarde
